codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: false

comment:
  layout: "reach,diff"
  require_changes: true
  hide_project_coverage: false

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: 90%  
        threshold: 0%
        informational: false