# --------------------------------------------------------------------------- #
cmake_path(
  GET CMAKE_CURRENT_LIST_DIR PARENT_PATH CHARMANDER_ROOT_DIR
)
cmake_path(
  APPEND CHARMANDER_ROOT_DIR "src" OUTPUT_VARIABLE CHARMANDER_SRC_DIR
)
cmake_path(
  APPEND CHARMANDER_ROOT_DIR "include" OUTPUT_VARIABLE CHARMANDER_INCLUDE_DIR
)
cmake_path(
  APPEND CHARMANDER_ROOT_DIR "tests" OUTPUT_VARIABLE CHARMANDER_TEST_DIR
)
cmake_path(
  APPEND CHARMANDER_ROOT_DIR "cli" OUTPUT_VARIABLE CHARMANDER_CLI_DIR
)